DROP TABLE IF EXISTS PROFIL_EVENEMENT;
DROP TABLE IF EXISTS UTILISATEUR_EVENEMENT;
DROP TABLE IF EXISTS UTILISATEUR_PROFIL;
DROP TABLE IF EXISTS UTILISATEUR;
DROP TABLE IF EXISTS PROFIL;
DROP TABLE IF EXISTS EVENEMENT;

CREATE TABLE IF NOT EXISTS UTILISATEUR
(
 	UTILISATEUR_ID VARCHAR(10) PRIMARY KEY NOT NULL,
	NOM VARCHAR(10),
	PRENOM VARCHAR(10),
	PSWD VARCHAR(40) NOT NULL, 
	SERVICE VARCHAR(15)
);

CREATE TABLE IF NOT EXISTS PROFIL
(
 	PROFIL_CODE VARCHAR(10) PRIMARY KEY NOT NULL,
	PROFIL_DESCRIPTION VARCHAR(250)
);

CREATE TABLE IF NOT EXISTS EVENEMENT
(
 	EVENEMENT_CODE VARCHAR(10) PRIMARY KEY NOT NULL,
	EVENEMENT_DESCRIPTION VARCHAR(250)
);

CREATE TABLE IF NOT EXISTS UTILISATEUR_PROFIL (
	UTILISATEUR_ID VARCHAR(10) UNIQUE NOT NULL,
	PROFIL_CODE varchar(10) NOT NULL,
	DATE_VALIDATION DATE NOT NULL,
	PRIMARY KEY (UTILISATEUR_ID, PROFIL_CODE),
	CONSTRAINT C1 FOREIGN KEY (UTILISATEUR_ID) REFERENCES UTILISATEUR (UTILISATEUR_ID) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT C2 FOREIGN KEY (PROFIL_CODE) REFERENCES PROFIL (PROFIL_CODE) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PROFIL_EVENEMENT (
	PROFIL_CODE VARCHAR(10) NOT NULL,
	EVENEMENT_CODE varchar(10) NOT NULL,
	NIV_HABILITATION VARCHAR(10) NOT NULL,
	PRIMARY KEY (PROFIL_CODE, EVENEMENT_CODE),
	CONSTRAINT C3 FOREIGN KEY (EVENEMENT_CODE) REFERENCES EVENEMENT (EVENEMENT_CODE) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT C4 FOREIGN KEY (PROFIL_CODE) REFERENCES PROFIL (PROFIL_CODE) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS UTILISATEUR_EVENEMENT (
	UTILISATEUR_ID VARCHAR(10) NOT NULL,
	EVENEMENT_CODE varchar(10) NOT NULL,
	DATE_VALIDATION DATE NOT NULL,
	NIV_HABILITATION VARCHAR(10) NOT NULL,
	PRIMARY KEY (UTILISATEUR_ID, EVENEMENT_CODE),
	CONSTRAINT C5 FOREIGN KEY (UTILISATEUR_ID) REFERENCES UTILISATEUR (UTILISATEUR_ID) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT C6 FOREIGN KEY (EVENEMENT_CODE) REFERENCES EVENEMENT (EVENEMENT_CODE) ON UPDATE CASCADE ON DELETE CASCADE
);

INSERT INTO UTILISATEUR VALUES ('ccc', 'n1', 'p1', 'pswd', 'info');
INSERT INTO UTILISATEUR_PROFIL VALUES ('ccc', 'consult', '2022-08-27');
INSERT INTO UTILISATEUR_EVENEMENT VALUES ('aaa', 'ev1', '2022-08-27', '1');